---
title: "2021年度の店舗別の販売個数"
author: "担当者"
date: "2021/7/30"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
# データを読み込んでグラフと表用のデータにする
# (17章3.3節参照)

tidy_hanbaikosu <- function(file_name){
  #読み込むファイル名を指定
  #file_name <- "hanbaikosu/2021年度A店舗.xlsx"

  #年度列と店舗列をファイル名から作成
  nendo <- str_extract(file_name,"\\d{4}(?=年度)")
  tenpo <- str_extract(file_name,"(?<=年度).+(?=店舗)")
  
  # ファイルを読み込んでtidyにする
  dat <- read_excel(file_name) %>% 
    pivot_longer(cols = !`味`, 
                 names_to = c("sex","age"),
                 names_sep = ":") %>% 
    mutate(nendo = nendo, tenpo = tenpo) %>% 
    select(nendo, tenpo, aji = `味`, everything())
  
  return(dat)
}

dat1 <- tidy_hanbaikosu("hanbaikosu/2021年度A店舗.xlsx")
dat2 <- tidy_hanbaikosu("hanbaikosu/2021年度B店舗.xlsx")
dat3 <- tidy_hanbaikosu("hanbaikosu/2021年度C店舗.xlsx")
dat4 <- tidy_hanbaikosu("hanbaikosu/2021年度D店舗.xlsx")
dat5 <- tidy_hanbaikosu("hanbaikosu/2021年度E店舗.xlsx")

dat <- bind_rows(dat1,dat2,dat3,dat4,dat5)

uriage <- dat %>% 
  group_by(nendo,tenpo) %>% 
  summarise(val = sum(value))

aji <- dat %>% 
  group_by(aji) %>% 
  summarise(val = sum(value))
```

## 2021年度の店舗別の売上

```{r}
barplot(uriage$val, names.arg = uriage$tenpo,xlab = "店舗名")
```

```{r}
uriage %>% 
  pivot_wider(id_cols = nendo, names_from =tenpo, values_from=val) %>% 
  knitr::kable()
```

## 味別の売上

```{r}
barplot(aji$val, names.arg = aji$aji, xlab="味")
```

```{r}
aji %>% rename("味" = aji, "売上個数" = val) %>% 
  knitr::kable()
```

